name: qucochemistry
channels:
  - defaults
  - conda-forge
  - psi4
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1c=h7b6447c_1
  - pip=19.1.1=py37_0
  - python=3.7.3=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - antlr4-python3-runtime==4.7.2
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - future==0.17.1
    - h5py==2.9.0
    - idna==2.8
    - immutables==0.6
    - ipykernel==5.1.1
    - ipython==7.6.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.0
    - jedi==0.14.1
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.3.1
    - jupyter-console==6.0.0
    - jupyter-core==4.5.0
    - kiwisolver==1.1.0
    - matplotlib==3.1.1
    - mistune==0.8.4
    - msgpack==0.6.1
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - networkx==2.3
    - notebook==6.0.0
    - numpy==1.15.4
    - openfermion==0.9.0
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pubchempy==1.0.4
    - pyquil==2.7.2
    - pyrsistent==0.15.3
    - python-dateutil==2.8.0
    - python-rapidjson==0.7.2
    - pyzmq==18.0.2
    - qtconsole==4.5.1
    - requests==2.22.0
    - rpcq==2.7.1
    - ruamel-yaml==0.15.100
    - scipy==1.2.0
    - send2trash==1.5.0
    - six==1.12.0
    - terminado==0.8.2
    - testpath==0.4.2
    - tornado==6.0.3
    - traitlets==4.3.2
    - typing==3.7.4
    - urllib3==1.25.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.0
